version: '3.8'
services:
  prime-spirals:
    image: prime-spirals
    #build:
    #  context: .
    #  dockerfile: Dockerfile
    ports:
      - "4000"
      #- "45892"
    networks:
      - app_network
    environment:
      - RELEASE_COOKIE=somepassword
    # environment:
    #  - ENV_VAR=value

networks:
  app_network:
    driver: bridge