services:
  main:
    image: prime-spirals
    ports:
      - "4000:4000"
    networks:
      - app_network
  additional-node:
    image: prime-spirals
    ports:
      - "4000"
    networks:
      - app_network
    
networks:
  app_network:
    driver: bridge